theme: jekyll-theme-minimal
title: Developer-Enabled Threat Modeling: Owning Your Role in Risk Averse Design
description: A book by Izar Tarandach and Matthew J. Coles
logo: cover.jpg
google_analytics: UA-175814987-1

